// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMKKMm-iPxb5rIJsHjN_JWn_rV6EcRUbc',
    appId: '1:207684430040:web:766dc3d9cc04bb3e7ccfad',
    messagingSenderId: '207684430040',
    projectId: 'recontaapp',
    authDomain: 'recontaapp.firebaseapp.com',
    storageBucket: 'recontaapp.firebasestorage.app',
    measurementId: 'G-7NQXVKEJ4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdM4A14dFrLzzrWjsb80AFUrUL3wD0fXA',
    appId: '1:207684430040:android:71e3276baf5266257ccfad',
    messagingSenderId: '207684430040',
    projectId: 'recontaapp',
    storageBucket: 'recontaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArvpXTiEPIdmKXAziO7h1BQ4DcFmitX3Q',
    appId: '1:207684430040:ios:6918fbe6896b104e7ccfad',
    messagingSenderId: '207684430040',
    projectId: 'recontaapp',
    storageBucket: 'recontaapp.firebasestorage.app',
    iosBundleId: 'com.example.recontaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArvpXTiEPIdmKXAziO7h1BQ4DcFmitX3Q',
    appId: '1:207684430040:ios:6918fbe6896b104e7ccfad',
    messagingSenderId: '207684430040',
    projectId: 'recontaapp',
    storageBucket: 'recontaapp.firebasestorage.app',
    iosBundleId: 'com.example.recontaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMKKMm-iPxb5rIJsHjN_JWn_rV6EcRUbc',
    appId: '1:207684430040:web:cc975c5e429a6c717ccfad',
    messagingSenderId: '207684430040',
    projectId: 'recontaapp',
    authDomain: 'recontaapp.firebaseapp.com',
    storageBucket: 'recontaapp.firebasestorage.app',
    measurementId: 'G-RBQHL0EJFG',
  );
}
